### PR TITLE
Chub 2650

### PR DESCRIPTION
**Pull request by tconway**
- Move global role to top level user key
- Determine verified value from presence of verification_has

This will also require updates to the Accounts services and the Service UI.

### CODE REVIEW

**Comment by mattijohn** [comment]
Looks fine

**Comment by Jimflip** [comment]
Why you no merge then?

**Comment by mattijohn** [comment]
The change will require migrating data in couch. We need to decide whether or not to merge this before or after we have sorted out our database migrations

**Comment by mattijohn** [comment]
@tconway I added a data migration for the User model, can you check it's OK?

**Comment by tconway** [comment]
Looks good to me. Will we be doing manual migration runs or is the plan to incorporate into provisioning?

**Comment by mattijohn** [comment]
I'm going to add it to provisioning

**Pull request merged**
